# Generated by Django 4.0.4 on 2022-05-21 12:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('House', '0002_rename_address_name_house_city_and_more'),
        ('Front', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime(2022, 5, 21, 12, 40, 30, 870521, tzinfo=utc))),
                ('house_slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='House.house')),
            ],
        ),
        migrations.DeleteModel(
            name='House',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='siteinfo',
            name='created_at',
        ),
        migrations.AddField(
            model_name='contact',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 21, 12, 40, 30, 867541, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 21, 12, 40, 30, 867541, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='siteservice',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 21, 12, 40, 30, 871515, tzinfo=utc)),
        ),
    ]
