# Generated by Django 4.0.4 on 2022-05-14 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Front', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteinfo',
            old_name='fullSiteColor',
            new_name='full_site_color',
        ),
        migrations.RenameField(
            model_name='siteinfo',
            old_name='mainColor',
            new_name='main_color',
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
