# Generated by Django 4.0.4 on 2022-05-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Front', '0002_rename_fullsitecolor_siteinfo_full_site_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='image4',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
