# Generated by Django 4.0.4 on 2022-05-18 15:21

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Front', '0002_rename_fullsitecolor_siteinfo_full_site_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='image1',
            new_name='photo_house',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='title1',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='delete_at',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='title2',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='title3',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='slider',
            name='contry',
            field=django_countries.fields.CountryField(default='Civ', max_length=2),
            preserve_default=False,
        ),
    ]
