# Generated by Django 4.0.4 on 2022-06-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Front', '0003_slider_image4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='latitude',
            field=models.DecimalField(decimal_places=10, max_digits=11),
        ),
        migrations.AlterField(
            model_name='contact',
            name='longitude',
            field=models.DecimalField(decimal_places=10, max_digits=11),
        ),
    ]
