# Generated by Django 4.0.4 on 2022-05-18 15:57

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Front', '0003_rename_created_at_slider_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='city',
            field=models.CharField(default='Abidjan', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='price',
            field=models.IntegerField(default=25, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slider',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 18, 15, 56, 51, 213455, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='slider',
            name='photo_house',
            field=models.ImageField(upload_to=''),
        ),
    ]
