# Generated by Django 4.0.4 on 2022-05-18 19:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Front', '0004_slider_city_slider_price_alter_slider_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 18, 19, 0, 44, 30423, tzinfo=utc)),
        ),
    ]
