# Generated by Django 4.0.4 on 2022-06-16 13:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Front', '0004_alter_contact_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 13, 45, 49, 166532, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='houseslide',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 13, 45, 49, 169533, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 13, 45, 49, 166532, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='siteservice',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 13, 45, 49, 172534, tzinfo=utc)),
        ),
    ]
