# Generated by Django 4.0.4 on 2022-06-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Front', '0005_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.TextField(),
        ),
    ]
