# Generated by Django 4.0.4 on 2022-05-18 19:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Front', '0005_alter_slider_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
                ('photo_house', models.ImageField(upload_to='')),
                ('created', models.DateTimeField(default=datetime.datetime(2022, 5, 18, 19, 52, 3, 781709, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='slider',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 18, 19, 52, 3, 780715, tzinfo=utc)),
        ),
    ]
