# Generated by Django 4.0.4 on 2022-05-18 20:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Front', '0006_siteservice_alter_slider_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteservice',
            old_name='photo_house',
            new_name='photo_service',
        ),
        migrations.AlterField(
            model_name='siteservice',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 18, 20, 2, 24, 204588, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='slider',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 18, 20, 2, 24, 202602, tzinfo=utc)),
        ),
    ]
