# Generated by Django 4.0.4 on 2022-05-18 21:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Front', '0008_house_delete_slider_alter_siteservice_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 18, 21, 29, 52, 969692, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='siteservice',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 18, 21, 29, 52, 970686, tzinfo=utc)),
        ),
    ]
