# Generated by Django 4.0.4 on 2022-06-22 11:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Front', '0014_alter_contact_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 22, 11, 39, 26, 185975, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='houseslide',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 22, 11, 39, 26, 186371, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 22, 11, 39, 26, 185481, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='siteservice',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 22, 11, 39, 26, 186744, tzinfo=utc)),
        ),
    ]
