# Generated by Django 4.0.4 on 2022-05-31 10:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Front', '0029_alter_contact_created_alter_houseslide_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseslide',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='houseslide',
            name='date_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='houseslide',
            name='photo_house',
            field=models.ImageField(default='1', upload_to=''),
            preserve_default=False,
        ),
    ]
