# Generated by Django 4.0.4 on 2022-06-15 12:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Front', '0029_alter_contact_created_alter_houseslide_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='created',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='delete_at',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='houseslide',
            name='created',
        ),
        migrations.RemoveField(
            model_name='siteinfo',
            name='created',
        ),
        migrations.RemoveField(
            model_name='siteinfo',
            name='delete_at',
        ),
        migrations.RemoveField(
            model_name='siteinfo',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='siteservice',
            name='created',
        ),
        migrations.AddField(
            model_name='contact',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 15, 12, 6, 51, 342101, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='contact',
            name='date_deleted',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='houseslide',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 15, 12, 6, 51, 343101, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='houseslide',
            name='date_deleted',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='houseslide',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='houseslide',
            name='photo_house',
            field=models.ImageField(default='ABC', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 15, 12, 6, 51, 340101, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='date_deleted',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='siteservice',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 15, 12, 6, 51, 344102, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='siteservice',
            name='date_deleted',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='siteservice',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
