# Generated by Django 4.0.4 on 2022-06-02 10:47

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Front', '0031_remove_houseslide_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSectionOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_one', models.CharField(max_length=255)),
                ('title_two', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='')),
                ('deleted', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AboutSectionTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_one', models.CharField(max_length=255)),
                ('title_two', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='')),
                ('deleted', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('number_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('fb_link', models.URLField(default='https://www.google.com/')),
                ('instagram_link', models.URLField(default='https://www.google.com/')),
                ('twitter_link', models.URLField(default='https://www.google.com/')),
                ('linkedin_link', models.URLField(default='https://www.google.com/')),
                ('photo', models.ImageField(upload_to='')),
                ('deleted', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='delete_at',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='dial_code',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='main_phone',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='site_contact',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='contact',
            name='deleted',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='number_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+2250779735640', max_length=128, region=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='fb_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='insta_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='linkedin_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='twitter_link',
            field=models.URLField(),
        ),
    ]
