# Generated by Django 4.0.4 on 2022-06-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Front', '0032_aboutsectionone_aboutsectiontwo_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsectionone',
            name='title_main',
            field=models.CharField(default='Exemple text', max_length=225),
        ),
    ]
