# Generated by Django 4.0.4 on 2022-06-02 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Front', '0033_aboutsectionone_title_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutsectionone',
            name='title_main',
        ),
    ]
