# Generated by Django 4.0.4 on 2022-06-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Front', '0034_remove_aboutsectionone_title_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='title',
            field=models.CharField(default='Exemple de titre', max_length=255),
        ),
    ]
