# Generated by Django 4.0.4 on 2022-05-21 12:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infoagent',
            name='created_at',
        ),
        migrations.AddField(
            model_name='infoagent',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 21, 12, 40, 30, 563581, tzinfo=utc)),
        ),
    ]
