# Generated by Django 4.0.4 on 2022-05-21 12:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_infoagent_created_at_infoagent_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoagent',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 21, 12, 43, 33, 199136, tzinfo=utc)),
        ),
    ]
