# Generated by Django 4.0.4 on 2022-05-21 12:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_infoagent_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoagent',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 21, 12, 43, 59, 352956, tzinfo=utc)),
        ),
    ]
