# Generated by Django 4.0.4 on 2022-05-21 17:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_infoagent_created_alter_infoagent_delete_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoagent',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 21, 17, 16, 16, 173902, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 21, 17, 16, 16, 168936, tzinfo=utc)),
        ),
    ]
