# Generated by Django 4.0.4 on 2022-05-21 18:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_infoagent_created_alter_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoagent',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 21, 18, 8, 15, 143541, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 21, 18, 8, 15, 138573, tzinfo=utc)),
        ),
    ]
