# Generated by Django 4.0.4 on 2022-05-23 10:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_alter_infoagent_created_alter_infoagent_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoagent',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 23, 10, 54, 41, 91836, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='infoagent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 23, 10, 54, 41, 86870, tzinfo=utc)),
        ),
    ]
