# Generated by Django 4.0.4 on 2022-05-27 11:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_alter_infoagent_created_alter_infoagent_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoagent',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 11, 34, 38, 572696, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 11, 34, 38, 568695, tzinfo=utc)),
        ),
    ]
