# Generated by Django 4.0.4 on 2022-06-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0029_alter_infoagent_created_alter_user_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infoagent',
            name='created',
        ),
        migrations.RemoveField(
            model_name='infoagent',
            name='delete_at',
        ),
        migrations.RemoveField(
            model_name='infoagent',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='delete_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='infoagent',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='infoagent',
            name='date_deleted',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='infoagent',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_deleted',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
