# Generated by Django 4.0.4 on 2022-05-21 12:42

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_infoagent_created_at_infoagent_created'),
        ('House', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='address_name',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='house',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='house',
            name='delete_at',
        ),
        migrations.RemoveField(
            model_name='house',
            name='price_payment',
        ),
        migrations.RemoveField(
            model_name='house',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='houseimage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='housepaymentperiod',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='housetype',
            name='created_at',
        ),
        migrations.AddField(
            model_name='house',
            name='area',
            field=models.IntegerField(default='25', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000000)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='contry',
            field=django_countries.fields.CountryField(default='FR', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 21, 12, 40, 30, 865554, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='house',
            name='info_agent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='customers.infoagent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='title',
            field=models.CharField(default='Exemple titre', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='houseimage',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 21, 12, 40, 30, 866548, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='housepaymentperiod',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 21, 12, 40, 30, 860587, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='housetype',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 21, 12, 40, 30, 860587, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='house',
            name='garage_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000000)]),
        ),
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000000)]),
        ),
        migrations.AlterField(
            model_name='house',
            name='rooms_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000000)]),
        ),
        migrations.AlterField(
            model_name='house',
            name='toillete_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000000)]),
        ),
    ]
