# Generated by Django 4.0.4 on 2022-05-19 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('House', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_house', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='house',
            name='house_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='House.housetype'),
        ),
        migrations.AddField(
            model_name='house',
            name='price_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='House.housepaymentperiod'),
        ),
    ]
