# Generated by Django 4.0.4 on 2022-06-04 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('House', '0002_alter_housepaymentperiod_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='price_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_payment_period', to='House.housepaymentperiod'),
        ),
    ]
