# Generated by Django 4.0.4 on 2022-05-27 14:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('House', '0010_alter_house_created_alter_houseimage_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealeStateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('isactive', models.BooleanField(default=True)),
                ('description', models.TextField(null=True)),
                ('created', models.DateTimeField(default=datetime.datetime(2022, 5, 27, 14, 54, 21, 836282, tzinfo=utc))),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='housetype',
            name='created',
        ),
        migrations.RemoveField(
            model_name='housetype',
            name='delete_at',
        ),
        migrations.RemoveField(
            model_name='housetype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='housetype',
            name='isactive',
        ),
        migrations.RemoveField(
            model_name='housetype',
            name='name',
        ),
        migrations.RemoveField(
            model_name='housetype',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='housetype',
            name='type_category',
            field=models.CharField(default='Location', max_length=225),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 14, 54, 21, 842280, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='houseimage',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 14, 54, 21, 843281, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='housepaymentperiod',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 14, 54, 21, 837281, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='house',
            name='real_estate_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='House.realestatetype'),
            preserve_default=False,
        ),
    ]
