# Generated by Django 4.0.4 on 2022-05-27 15:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0020_alter_infoagent_created_alter_user_created_at'),
        ('House', '0012_alter_house_created_alter_houseimage_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 15, 22, 30, 88148, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='houseimage',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 15, 22, 30, 89148, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='housepaymentperiod',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 15, 22, 30, 83148, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='realestatetype',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 15, 22, 30, 82148, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='realestatetype',
            name='delete_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='realestatetype',
            name='description',
            field=models.TextField(default='Ceci est une test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='realestatetype',
            name='updated_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.CreateModel(
            name='LatestNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=50)),
                ('available_date', models.DateTimeField()),
                ('created', models.DateTimeField(default=datetime.datetime(2022, 5, 27, 15, 22, 30, 90148, tzinfo=utc))),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('info_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.infoagent')),
                ('reale_state_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='House.realestatetype')),
            ],
        ),
    ]
