# Generated by Django 4.0.4 on 2022-05-27 15:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('House', '0014_alter_house_created_alter_houseimage_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 15, 44, 29, 228501, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='houseimage',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 15, 44, 29, 229501, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='housepaymentperiod',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 15, 44, 29, 223501, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 15, 44, 29, 230501, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='realestatetype',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 15, 44, 29, 222500, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='realestatetype',
            name='delete_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='realestatetype',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
