# Generated by Django 4.0.4 on 2022-05-27 16:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('House', '0016_alter_house_created_alter_houseimage_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='latest_news_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='latestnews',
            name='house',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='House.house'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 16, 0, 13, 454252, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='houseimage',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 16, 0, 13, 455257, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='housepaymentperiod',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 16, 0, 13, 449258, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 16, 0, 13, 456253, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='realestatetype',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 16, 0, 13, 448218, tzinfo=utc)),
        ),
    ]
