# Generated by Django 4.0.4 on 2022-05-27 16:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('House', '0017_house_latest_news_bool_latestnews_house_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 16, 0, 56, 601698, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='houseimage',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 16, 0, 56, 602698, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='housepaymentperiod',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 16, 0, 56, 597698, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 16, 0, 56, 603758, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='realestatetype',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 16, 0, 56, 596699, tzinfo=utc)),
        ),
    ]
