# Generated by Django 4.0.4 on 2022-05-27 16:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('House', '0018_alter_house_created_alter_houseimage_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latestnews',
            name='reale_state_type',
        ),
        migrations.AddField(
            model_name='house',
            name='reale_state_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='House.realestatetype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='house',
            name='real_estate_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='House.realestatetype'),
        ),
        migrations.AlterField(
            model_name='houseimage',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='housepaymentperiod',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='realestatetype',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
