# Generated by Django 4.0.4 on 2022-05-27 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('House', '0019_remove_latestnews_reale_state_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='reale_state_type',
        ),
    ]
