# Generated by Django 4.0.4 on 2022-05-31 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('House', '0020_remove_house_reale_state_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='real_estate_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='House.realestatetype'),
        ),
    ]
