# Generated by Django 4.0.4 on 2022-06-15 12:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('House', '0020_remove_house_reale_state_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='created',
        ),
        migrations.RemoveField(
            model_name='housepaymentperiod',
            name='created',
        ),
        migrations.RemoveField(
            model_name='housepaymentperiod',
            name='delete_at',
        ),
        migrations.RemoveField(
            model_name='housepaymentperiod',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='latestnews',
            name='created',
        ),
        migrations.RemoveField(
            model_name='latestnews',
            name='delete_at',
        ),
        migrations.RemoveField(
            model_name='latestnews',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='realestatetype',
            name='created',
        ),
        migrations.RemoveField(
            model_name='realestatetype',
            name='delete_at',
        ),
        migrations.RemoveField(
            model_name='realestatetype',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='house',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 15, 12, 6, 51, 337101, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='house',
            name='date_deleted',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='house',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='housepaymentperiod',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 15, 12, 6, 51, 323518, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='housepaymentperiod',
            name='date_deleted',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='housepaymentperiod',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='housetype',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 15, 12, 6, 51, 322519, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='housetype',
            name='date_deleted',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='housetype',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='latestnews',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 15, 12, 6, 51, 339101, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='latestnews',
            name='date_deleted',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='latestnews',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='realestatetype',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 15, 12, 6, 51, 321518, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='realestatetype',
            name='date_deleted',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='realestatetype',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='real_estate_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='House.realestatetype'),
        ),
    ]
