# Generated by Django 4.0.4 on 2022-06-02 11:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('House', '0021_alter_house_real_estate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='beds',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
